<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Platforms>AnyCPU;x64</Platforms>
    <RootNamespace>MatrixScreenSaver</RootNamespace>
    <AssemblyName>MatrixScreenSaver</AssemblyName>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <Company>ecth oo'</Company>
    <Product>MatrixScreenSaver</Product>
    <Trademark>ecth oo'</Trademark>
    <Copyright>Copyright © 2017</Copyright>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <!-- Windows only offers .scr files as screensavers. -->
  <Target Name="CopyAsScreenSaver" AfterTargets="Publish">
    <Copy SourceFiles="$(PublishDir)$(AssemblyName).exe" DestinationFiles="$(PublishDir)$(AssemblyName).scr" />
  </Target>

</Project>
